<?php
$page_name = "Privacy Policy";
$page_slug = 'privacy-policy';
$page_thumbnail = "https://example.com/image.jpg";
include '../inc/functions.php';
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <base href="../">
        <title><?php echo $page_title;?></title>
        <?php include '../inc/stylesheet.php';?>
    </head>
    <body>
        <?php include '../inc/navbar.php';?>
        <main class="app" id="app">

            <section class="" id="">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-12 col-md-11 col-xl-9 col-xxl-7 px-4">
                            <div class="text-editor">
                                <h1>Slotmega888.app Privacy Policy</h1>
                                <p>Effective Date: January 1, 2025</p>
                                <p>At <b>slotmega888.app</b>, your privacy is our top priority. We are fully committed to protecting your personal information and ensuring a secure, transparent, and respectful environment for all our users.</p>
                                <p>This Privacy Policy explains how we collect, use, store, and protect your data in connection with our services as an official Mega888 kiosk agent in Malaysia.</p>
                                <p>&nbsp;</p>
                                <P><b>1. Information We Collect</b></P>
                                <p>We collect only the necessary information required to create and manage your Mega888 account, support your transactions, and enhance your user experience.</p>
                                <p><b>Information we may collect includes:</b></p>
                                <ul>
                                    <li>Name or nickname (optional)</li>
                                    <li>Phone number (for registration and support)</li>
                                    <li>Game ID and login credentials (generated by us)</li>
                                    <li>Deposit and withdrawal records</li>
                                    <li>Communication history with our support team</li>
                                    <li>IP address and device type (for security monitoring)</li>
                                </ul>
                                <p>We do not collect sensitive data such as IC numbers, passwords to other accounts, credit card numbers, or unnecessary personal details.</p>
                                <p>We do not use your information for third-party advertising or unrelated marketing.</p>
                                <p>&nbsp;</p>
                                <p><b>2. How We Use Your Information</b></p>
                                <p>We use your data only for purposes that serve your Mega888 experience:</p>
                                <ul>
                                    <li>To generate and manage your game ID</li>
                                    <li>To confirm deposits and withdrawals</li>
                                    <li>To process bonus and promotion eligibility</li>
                                    <li>To verify account ownership in case of disputes</li>
                                    <li>To improve site security and prevent abuse</li>
                                    <li>To comply with regulatory requirements</li>
                                </ul>
                                <p>We do not use your information for third-party advertising or unrelated marketing.</p>
                                <p>&nbsp;</p>
                                <p><b>3. Data Sharing and Third Parties</b></p>
                                <p>We do <b>not</b> sell, trade, or rent your personal information to any third parties.</p>
                                <p>Your information is only shared under the following conditions:</p>
                                <ul>
                                    <li>With our internal support team to resolve issues</li>
                                    <li>With payment verification services (when required by law)</li>
                                    <li>With authorities if legally required to prevent fraud or comply with investigations</li>
                                </ul>
                                <p>All shared data is handled with strict confidentiality.</p>
                                <p>&nbsp;</p>
                                <p><b>4. How We Protect Your Data</b></p>
                                <p>We use industry-standard security practices to safeguard your data:</p>
                                <ul>
                                    <li><b>AES-256 encryption </b>for storage of communication and transaction records</li>
                                    <li><b>End-to-end encryption </b>in WhatsApp and Telegram communication</li>
                                    <li>Access to your data is restricted to authorized staff only</li>
                                    <li>Regular audits are conducted to ensure policy compliance</li>
                                </ul>
                                <p>We do not store any banking login credentials or payment passwords.</p>
                                <p>&nbsp;</p>
                                <p><b>5. Data Retention Policy</b></p>
                                <p>We keep your records only for as long as needed:</p>
                                <ul>
                                    <li>Game IDs and transaction logs are retained for operational and legal reasons</li>
                                    <li>Communication records are stored for support resolution purposes</li>
                                    <li>You may request permanent deletion of your account at any time</li>
                                </ul>
                                <p>Once data is no longer needed, it is permanently deleted from our systems.</p>
                                <p>&nbsp;</p>
                                <p><b>6. User Rights and Access</b></p>
                                <p>As a user of slotmega888.app, you have the right to:</p>
                                <ul>
                                    <li>Request access to your personal data</li>
                                    <li>Ask for corrections to any incorrect details</li>
                                    <li>Request deletion of your data (subject to verification)</li>
                                    <li>Opt-out of promotional messages at any time</li>
                                </ul>
                                <p>To exercise these rights, contact our support team via WhatsApp or Telegram.</p>
                                <p>&nbsp;</p>
                                <p><b>7. Cookies and Tracking</b></p>
                                <p>We do not use cookies or browser tracking technologies on this site.</p>

                                <p>We only track anonymous visit data for security and traffic monitoring.</p>
                                <p>&nbsp;</p>
                                <p><b>8. Protecting Minors and At-Risk Users</b></p>
                                <p>We do not allow access to users under the age of <b>21</b>. We also do not collect or store data from minors. If we discover such data, it is deleted immediately.</p>
                                <p>We actively discourage high-risk users from playing, including those under financial stress or with gambling-related concerns.</p>
                                <p>&nbsp;</p>
                                <p><b>9. Changes to This Policy</b></p>
                                <p>This Privacy Policy may be updated from time to time for legal, operational, or platform-related reasons.</p>
                                <p>Changes will be published clearly on this page. By continuing to use our platform, you accept the most current version.</p>
                                <p>&nbsp;</p>
                                <p><b>10. Contact Us</b></p>
                                <p>For any questions or concerns regarding your privacy or how we handle your data, please contact us directly:</p>
                                <p><b>Support Hours: </b>Daily, 10:00 AM – 12:00 AM</p>
                                <p><b>Email: </b>support@slotmega888.app</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <?php include '../inc/footer.php';?>
        <?php include '../inc/popup-share-this.php';?>
    </body>
</html>